#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.imgmath',
    'numpydoc',
    'autoapi.extension',
]

# use typehints in the API docs
# autodoc_typehints = 'description'

# this needed for numpydoc I think
numpydoc_show_class_members = False
numpydoc_show_inherited_class_members = False

# Autoapi settings
# Note we don't actually create the auto-generated API pages for now,
# instead we write our own pages (e.g. api/hcam_obsutils.rst, scripts in scripts.rst)
autoapi_dirs = ['../../src/hcam_obsutils']
autoapi_generate_api_docs = True
#autoapi_ignore = ['*scripts*']
autoapi_root = "api"
autoapi_python_class_content = "both"
autoapi_member_order = "bysource"

# don't include scripts in the API docs, we write our own page for them
def skip_scripts(app, what, name, obj, skip, options):
    if "scripts" in name:
       skip = True
    return skip

def setup(sphinx):
   sphinx.connect("autoapi-skip-member", skip_scripts)

# number figures
numfig = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
source_suffix = {'.rst': 'restructuredtext'}

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'HiPERCAM observation utilities'
copyright = '2026, S.P Littlefair'
author = 'S.P Littlefair and Martin J. Dyer'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
try:
    # Try to get version from installed package first
    from importlib.metadata import version as _version
    release = _version('hcam_obsutils')
    print(f"[Sphinx] Using installed package version: {release}")
except ImportError:
    # Fallback to setuptools_scm if package not installed
    try:
        from setuptools_scm import get_version
        release = get_version(root='../..', relative_to=__file__)
        print(f"[Sphinx] Using setuptools_scm version: {release}")
    except (ImportError, LookupError) as e:
        # Final fallback to a default version
        release = "unknown"
        print(f"[Sphinx] WARNING: Could not determine version ({e}), using: {release}")
version = release

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = 'alabaster'
#html_theme = 'classic'
html_theme = 'sphinx_rtd_theme'
#html_theme = 'bootstrap-astropy'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
#html_theme_options = {
#    'logotext2': '',  # orange, light
#    'logotext3': ':docs',   # white,  light
#    'astropy_project_menubar': False
#}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
#html_sidebars = {
#    '**': [
#        'relations.html',  # needs 'show_related': True theme option to display
#        'searchbox.html',
#    ]
#}
html_sidebars = {
    '**': [
        'globaltoc.html', 'relations.html',
        'sourcelink.html', 'searchbox.html'],
}

